#!/usr/bin/env node

var Log = require('./log');
var log = new Log();
log.setLevel('verbose');

log.setOption('d', true);
log.d('D!!!!');
log.verbose('blergh!', {key: { secondKey: {innerObject: 'value'}, otherSecondKey: {innerObject: 'value2'}}});
log.info('blergh!', {key: { secondKey: 'value' }});
log.warn('blergh!', {key: { secondKey: 'value' }});
log.error('blergh!', {key: { secondKey: 'value' }});
log.fatal('blergh!', {key: { secondKey: 'value' }});
process.exit();
