export const FORM_UPDATE_VALUE = 'FORM_UPDATE_VALUE';
export const FORM_UPDATE_LIST = 'FORM_UPDATE_LIST';
export const TOGGLE_LIST_ITEMS = 'TOGGLE_LIST_ITEMS';
export const FORM_RESET = 'FORM_RESET';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const DISPLAY_FORM_ERROR = 'DISPLAY_FORM_ERROR';

export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_TOURNAMENT_SUCCESS = 'FETCH_TOURNAMENT_SUCCESS';
export const UPDATE_SEEDS = 'UPDATE_SEEDS';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAILURE = 'CREATE_TOURNAMENT_FAILURE';

export const SUBMIT_SEEDS_SUCCESS = 'SUBMIT_SEEDS_SUCCESS';
export const SUBMIT_SEEDS_FAILURE = 'SUBMIT_SEEDS_FAILURE';


// localStorage property for the auth token
export const LOCAL_STORAGE_PROPERTY = 'ki-state';


export const ItemTypes = {
	DRAG_CHARACTER: 'draggableCharacter'
};
