export const FORM_UPDATE_VALUE = 'FORM_UPDATE_VALUE';
export const FORM_UPDATE_LIST = 'FORM_UPDATE_LIST';
export const TOGGLE_LIST_ITEMS = 'TOGGLE_LIST_ITEMS';
export const FORM_RESET = 'FORM_RESET';
export const POP_FORM_REASON = 'POP_TOURNAMENT_REASON';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const DISPLAY_FORM_ERROR = 'DISPLAY_FORM_ERROR';

export const TOGGLE_DRAFT_FILTER = 'TOGGLE_DRAFT_FILTER';

export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_TOURNAMENT_SUCCESS = 'FETCH_TOURNAMENT_SUCCESS';
export const UPDATE_SEEDS = 'UPDATE_SEEDS';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAILURE = 'CREATE_TOURNAMENT_FAILURE';

export const SUBMIT_SEEDS_SUCCESS = 'SUBMIT_SEEDS_SUCCESS';
export const SUBMIT_SEEDS_FAILURE = 'SUBMIT_SEEDS_FAILURE';

export const DRAFT_CHARACTER_SUCCESS = 'DRAFT_CHARACTER_SUCCESS';
export const DRAFT_CHARACTER_FAILURE = 'DRAFT_CHARACTER_FAILURE';

export const SUBMIT_GAME_SUCCESS = 'SUBMIT_GAME_SUCCESS';
export const SUBMIT_GAME_FAILURE = 'SUBMIT_GAME_FAILURE';

export const UNDO_LAST_GAME_SUCCESS = 'UNDO_LAST_GAME_SUCCESS';
export const UNDO_LAST_GAME_FAILURE = 'UNDO_LAST_GAME_FAILURE';

export const UPDATE_MATCHUPS_SUCCESS = 'UPDATE_MATCHUPS_SUCCESS';
export const UPDATE_MATCHUPS_FAILURE = 'UPDATE_MATCHUPS_FAILURE';

export const UPDATE_INSPECT_STATE = 'UPDATE_INSPECT_STATE';

// coins
export const REMATCH_SUCCESS = 'REMATCH_SUCCESS';
export const REMATCH_FAILURE = 'REMATCH_FAILURE';
export const ODDSMAKER_SUCCESS = 'ODDSMAKER_SUCCESS';
export const ODDSMAKER_FAILURE = 'ODDSMAKER_FAILURE';
export const USE_INSPECT_SUCCESS = 'USE_INSPECT_SUCCESS';
export const USE_INSPECT_FAILURE = 'USE_INSPECT_FAILURE';
export const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS';
export const DECREMENT_FAILURE = 'DECREMENT_FAILURE';
export const POP_TOURNAMENT_REASON = 'POP_TOURNAMENT_REASON';

// localStorage property for the auth token
export const LOCAL_STORAGE_PROPERTY = 'ki-state';


export const ItemTypes = {
	DRAG_CHARACTER: 'draggableCharacter',
	DRAGGABLE_INSPECT_CHARACTER: 'draggableInspectCharacter'
};

export const ERROR_RESET_TIME = 5000;
